### ISSUE TITLE
Synchronization step

### ISSUE THREAD

**Issue by AbdelwahabFawzyMohamed** [ctarver/ILA-DPD#6]
I can't understand the idea behind these mathematical equations?! the methodology ?!             
%Set up an LS estimation for figuring out a subsample delay.
X = [y [0; y(1:end-1)]];
coeffs = (X'*X) \ (X'*x);
y = X*coeffs;

**Comment by ctarver** [comment]
The main idea is this: there will be a subsample delay after sampling the RF. To line up the output to the input, I first do a course sample alignment. Then, in the step you mention, I do a subsample alignment. I assume that a linear interpolation can be used to fit the subsample delay. If the subsample delay is 7/10ths of a clock cycle, then in the case of a linear interpolation, the correction will be something like 70% one sample and 30% the next. By setting up the above least square estimation problem, we can learn the coeffs that fit the output and a delayed version of the output to the input. 

To perfectly represent what I am trying to do, we'd need to restrict coeff(1) + coeff(2) =1, and we'd need to make them be only real-valued. Even though I didn't explicitly make this restriction, I've found that they tend to obey this close enough so I haven't worried about it.
